import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AXIS_TITLES } from '@political-dialogue/shared';
function AxisRow({ axis, score, compareScore, showLabels = true }) {
    const title = AXIS_TITLES[axis];
    return (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm font-medium text-gray-700", children: title }), _jsxs("span", { className: "text-xs text-gray-400", children: [Math.round(score), "/100"] })] }), _jsxs("div", { className: "relative h-4 rounded-full bg-gradient-to-r from-blue-200 via-purple-100 to-red-200", children: [_jsx("div", { className: "absolute top-1/2 -translate-y-1/2 w-4 h-4 rounded-full bg-violet-600 border-2 border-white shadow-md transition-all", style: { left: `calc(${score}% - 8px)` }, title: `Your score: ${Math.round(score)}` }), compareScore !== undefined && (_jsx("div", { className: "absolute top-1/2 -translate-y-1/2 w-4 h-4 rounded-full bg-amber-500 border-2 border-white shadow-md transition-all", style: { left: `calc(${compareScore}% - 8px)` }, title: `Their score: ${Math.round(compareScore)}` }))] }), showLabels && (_jsxs("div", { className: "flex justify-between text-xs text-gray-400", children: [_jsx("span", { children: "Progressive" }), _jsx("span", { children: "Conservative" })] }))] }));
}
const AXES = ['economic', 'social', 'government', 'environment', 'foreign'];
export function SpectrumChart({ scores, compareScores, showLabels = true }) {
    return (_jsxs("div", { className: "space-y-5", children: [compareScores && (_jsxs("div", { className: "flex items-center gap-4 text-xs text-gray-500 mb-2", children: [_jsxs("span", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "w-3 h-3 rounded-full bg-violet-600 inline-block" }), " You"] }), _jsxs("span", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "w-3 h-3 rounded-full bg-amber-500 inline-block" }), " Your match"] })] })), AXES.map((axis) => (_jsx(AxisRow, { axis: axis, score: scores[axis], compareScore: compareScores?.[axis], showLabels: showLabels }, axis)))] }));
}
